apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: auth-service-config
- path: secret-patch.yaml
  target:
    kind: Secret
    name: auth-service-secrets
- target:
    kind: Middleware
    name: forward-auth
  patch: |-
    - op: replace
      path: /spec/forwardAuth/address
      value: http://auth-service.bbapp-prod.svc.cluster.local:80/forward-auth

namespace: bbapp-prod

images:
- name: asia-south1-docker.pkg.dev/bb-app-461714/bbapp-images/auth-service
  newName: asia-south1-docker.pkg.dev/light-depot-471209-j7/bbapp-images/auth-service