apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  APP_ENV: "staging"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "auth_service"
  DB_USER: "authuser"
  DB_PASSWORD: "StgAuth2024!"
  REDIS_ADDR: "redis-service:6379"
  PORT: "3001"
  NOTIFICATION_SERVICE_URL: "http://notification-service:80"
  FIREBASE_PROJECT_ID: "bb-app-461714-76b5a"
  GOOGLE_OAUTH_CLIENT_ID: "1032936072738-8b8k0v3qj7f0c9v8r2h5l4n6m7p9q1s2.apps.googleusercontent.com"
  GOOGLE_OAUTH_IOS_CLIENT_ID: "YOUR_STAGING_GOOGLE_IOS_CLIENT_ID"
  GOOGLE_OAUTH_ANDROID_CLIENT_ID: "YOUR_STAGING_GOOGLE_ANDROID_CLIENT_ID"
