apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  DB_HOST: "REPLACE_MYSQL_HOST"
  DB_PORT: "3306"
  DB_NAME: "auth_service"
  REDIS_ADDR: "REPLACE_REDIS_ADDR"
  PORT: "3001"
  APP_ENV: "REPLACE_ENVIRONMENT"
  NOTIFICATION_SERVICE_URL: "REPLACE_NOTIFICATION_SERVICE_URL"
  FIREBASE_PROJECT_ID: "REPLACE_FIREBASE_PROJECT_ID"
  GOOGLE_OAUTH_CLIENT_ID: "REPLACE_GOOGLE_CLIENT_ID"
  GOOGLE_OAUTH_IOS_CLIENT_ID: "REPLACE_GOOGLE_IOS_CLIENT_ID"
  GOOGLE_OAUTH_ANDROID_CLIENT_ID: "REPLACE_GOOGLE_ANDROID_CLIENT_ID"
