apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bbapp-dev

resources:
- ../../base

patches:
- path: configmap-patch.yaml
- path: secret-patch.yaml
- target:
    kind: Middleware
    name: forward-auth
  patch: |-
    - op: replace
      path: /spec/forwardAuth/address
      value: http://auth-service.bbapp-dev.svc.cluster.local:80/forward-auth
